import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Copy, ExternalLink, LayoutList, Link2, MapPin, RefreshCw, X } from "lucide-react";
import { useListCities } from "@workspace/api-client-react";
import { authFetch, useAuth } from "@/lib/auth";
import { ErrorState, LoadingRows, OpsShell, PageHeading, StatusPill } from "@/components/ops-shell";

type EventRow = { id: number; googleHtmlLink: string | null; title: string; description: string | null; location: string | null; startsAt: string; endsAt: string; cityId: number; cityName: string; regionName: string; status: string };
type CalendarView = "list" | "week";
async function read<T>(response: Response): Promise<T> { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "Não foi possível concluir a operação."); return body as T; }

function startOfWeek(date: Date) { const result = new Date(date); result.setHours(0, 0, 0, 0); const day = result.getDay(); result.setDate(result.getDate() - (day === 0 ? 6 : day - 1)); return result; }
function dateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function weekLabel(date: Date) { const end = new Date(date); end.setDate(end.getDate() + 6); return `${date.toLocaleDateString("pt-BR", { day: "2-digit", month: "short" })} — ${end.toLocaleDateString("pt-BR", { day: "2-digit", month: "short", year: "numeric" })}`; }
function eventDateKey(event: EventRow) { return dateKey(new Date(event.startsAt)); }

export default function AgendaPage() {
  const { can } = useAuth();
  const cities = useListCities();
  const [events, setEvents] = useState<EventRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [notice, setNotice] = useState<EventRow | null>(null);
  const [view, setView] = useState<CalendarView>("list");
  const [weekStart, setWeekStart] = useState(() => startOfWeek(new Date()));
  const [shareLink, setShareLink] = useState("");
  const [shareMessage, setShareMessage] = useState("");

  async function load() {
    setLoading(true); setError("");
    try {
      const rows = await read<EventRow[]>(await authFetch("/api/calendar/events"));
      setEvents(rows);
      const pending = rows.find((event) => event.status === "pending" && !localStorage.getItem(`ea-event-seen-${event.id}`));
      if (pending) setNotice(pending);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível carregar a agenda."); }
    finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, []);
  async function sync() { try { await read(await authFetch("/api/calendar/sync", { method: "POST" })); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível sincronizar."); } }
  async function acknowledge(event: EventRow) { localStorage.setItem(`ea-event-seen-${event.id}`, "1"); await authFetch(`/api/calendar/events/${event.id}/acknowledge`, { method: "POST" }).catch(() => undefined); setNotice(null); }
  async function createShareLink() {
    setShareMessage("");
    try {
      const share = await read<{ token: string }>(await authFetch("/api/calendar/shares", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ weekStart: dateKey(weekStart), label: `Agenda de ${weekLabel(weekStart)}` }) }));
      const base = import.meta.env.BASE_URL.endsWith("/") ? import.meta.env.BASE_URL : `${import.meta.env.BASE_URL}/`;
      setShareLink(`${window.location.origin}${base}agenda/compartilhada/${share.token}`);
      setShareMessage("Link criado. Copie e envie para o Edson.");
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível criar o link da agenda."); }
  }
  async function copyShareLink() {
    if (!shareLink) return;
    await navigator.clipboard?.writeText(shareLink);
    setShareMessage("Link copiado.");
  }
  const days = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(weekStart); date.setDate(date.getDate() + index); return date; }), [weekStart]);
  const weekEvents = events.filter((event) => { const key = eventDateKey(event); return key >= dateKey(weekStart) && key <= dateKey(days[6]); });

  if (loading) return <OpsShell><PageHeading eyebrow="Agenda / território" title="Agenda da campanha" description="Eventos criados pelo Edson Albertassi ou pelo administrador aparecem aqui por cidade." /><LoadingRows count={4} /></OpsShell>;
  if (error && !events.length) return <OpsShell><PageHeading eyebrow="Agenda / território" title="Agenda da campanha" description="Eventos criados pelo Edson Albertassi ou pelo administrador aparecem aqui por cidade." /><ErrorState label={error} onRetry={() => void load()} /></OpsShell>;
  return <OpsShell>
    <PageHeading eyebrow="Agenda / território" title="Agenda da campanha" description="Consulte a lista completa ou organize os compromissos em uma visão semanal." action={<div className="flex flex-wrap gap-2">{can("calendar:manage") && <><button onClick={() => void sync()} className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-3 text-xs font-extrabold"><RefreshCw size={14} /> Sincronizar</button><button onClick={() => setShowCreate(true)} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-3 text-xs font-extrabold text-primary-foreground">Novo evento</button></>}</div>} />
    {error && <p className="mb-4 rounded-xl bg-destructive/5 p-3 text-xs font-bold text-destructive">{error}</p>}
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-border bg-card p-3">
      <div className="flex items-center gap-2"><button onClick={() => setView("list")} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-extrabold ${view === "list" ? "bg-secondary text-primary" : "text-muted-foreground hover:bg-muted"}`}><LayoutList size={14} /> Lista</button><button onClick={() => setView("week")} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-extrabold ${view === "week" ? "bg-secondary text-primary" : "text-muted-foreground hover:bg-muted"}`}><CalendarDays size={14} /> Calendário semanal</button></div>
      {view === "week" && <div className="flex items-center gap-2"><button onClick={() => setWeekStart((date) => { const next = new Date(date); next.setDate(next.getDate() - 7); return next; })} className="rounded-lg border border-border p-2 hover:bg-muted" aria-label="Semana anterior"><ChevronLeft size={15} /></button><span className="min-w-[190px] text-center text-xs font-extrabold capitalize">{weekLabel(weekStart)}</span><button onClick={() => setWeekStart((date) => { const next = new Date(date); next.setDate(next.getDate() + 7); return next; })} className="rounded-lg border border-border p-2 hover:bg-muted" aria-label="Próxima semana"><ChevronRight size={15} /></button></div>}
    </div>
    {view === "week" ? <div className="overflow-x-auto rounded-2xl border border-border bg-card p-3"><div className="grid min-w-[980px] grid-cols-7 gap-2">{days.map((day) => { const key = dateKey(day); const dayEvents = weekEvents.filter((event) => eventDateKey(event) === key); return <section key={key} className="min-h-[430px] rounded-xl bg-muted/35 p-2"><header className="border-b border-border px-2 pb-3"><p className="text-[10px] font-extrabold uppercase text-muted-foreground">{day.toLocaleDateString("pt-BR", { weekday: "short" })}</p><p className="mt-1 text-lg font-extrabold">{day.getDate()}</p></header><div className="space-y-2 pt-2">{dayEvents.map((event) => <article key={event.id} className="rounded-lg border border-border bg-card p-2 shadow-sm"><p className="text-[10px] font-extrabold text-primary">{new Date(event.startsAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</p><p className="mt-1 text-xs font-extrabold leading-4">{event.title}</p><p className="mt-1 text-[10px] text-muted-foreground">{event.cityName}</p>{event.location && <p className="mt-1 truncate text-[10px] text-muted-foreground">{event.location}</p>}</article>)}</div></section>; })}</div></div> : <div className="space-y-3">{events.length ? events.map((event) => <article key={event.id} className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-secondary text-primary"><CalendarDays size={18} /></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-base font-extrabold">{event.title}</h2><StatusPill tone={event.status === "pending" ? "warning" : "success"}>{event.status === "pending" ? "Pendente" : event.status}</StatusPill></div><p className="mt-2 text-xs font-bold">{new Date(event.startsAt).toLocaleString("pt-BR")} — {new Date(event.endsAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><MapPin size={13} /> {event.cityName} · {event.regionName}{event.location ? ` · ${event.location}` : ""}</p>{event.description && <p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">{event.description}</p>}</div></div>{event.googleHtmlLink && <a href={event.googleHtmlLink} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-extrabold hover:bg-muted">Abrir Google Calendar <ExternalLink size={13} /></a>}</div></article>) : <div className="rounded-2xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">Nenhum evento da agenda foi encontrado para o seu território.</div>}</div>}
    {can("calendar:manage") && <section className="mt-5 rounded-2xl border border-[#b8d6e8] bg-[#eaf2f8] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="flex items-center gap-2 text-sm font-extrabold text-primary"><Link2 size={16} /> Compartilhar semana com Edson Albertassi</p><p className="mt-1 text-xs text-slate-600">Crie um link somente para a semana selecionada na visão de calendário.</p></div><button onClick={() => void createShareLink()} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-xs font-extrabold text-primary-foreground">Gerar link da semana</button></div>{shareLink && <div className="mt-4 flex flex-col gap-2 sm:flex-row"><input readOnly value={shareLink} className="h-10 min-w-0 flex-1 rounded-lg border border-[#b8d6e8] bg-white px-3 text-xs text-slate-600" /><button onClick={() => void copyShareLink()} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-primary bg-white px-4 text-xs font-extrabold text-primary"><Copy size={14} /> Copiar link</button></div>}{shareMessage && <p className="mt-2 text-xs font-bold text-primary">{shareMessage}</p>}</section>}
    {showCreate && <CreateEventDialog cities={cities.data ?? []} onClose={() => setShowCreate(false)} onCreated={(event) => { setEvents((current) => [...current, event].sort((a, b) => a.startsAt.localeCompare(b.startsAt))); setShowCreate(false); setNotice(event); }} />}
    {notice && <div className="fixed inset-0 z-50 flex items-center justify-center bg-primary/35 p-4"><section className="w-full max-w-md rounded-2xl bg-card p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="mono-label text-primary">Aviso da sua cidade</p><h2 className="mt-1 text-xl font-extrabold">{notice.title}</h2></div><button onClick={() => void acknowledge(notice)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted" aria-label="Fechar aviso"><X size={18} /></button></div><p className="mt-4 text-sm leading-6 text-muted-foreground">Haverá uma agenda de campanha em <strong className="text-foreground">{notice.cityName}</strong> em {new Date(notice.startsAt).toLocaleString("pt-BR")}{notice.location ? `, no local ${notice.location}` : ""}.</p>{notice.description && <p className="mt-3 rounded-xl bg-muted p-3 text-xs leading-5">{notice.description}</p>}<button onClick={() => void acknowledge(notice)} className="mt-6 h-11 w-full rounded-lg bg-primary text-sm font-extrabold text-primary-foreground">Entendi</button></section></div>}
  </OpsShell>;
}

function CreateEventDialog({ cities, onClose, onCreated }: { cities: Array<{ id: number; name: string; regionName: string }>; onClose: () => void; onCreated: (event: EventRow) => void }) {
  const [form, setForm] = useState({ title: "", description: "", location: "", cityId: "", startsAt: "", endsAt: "" });
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); try { onCreated(await read<EventRow>(await authFetch("/api/calendar/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, cityId: Number(form.cityId), startsAt: new Date(form.startsAt).toISOString(), endsAt: new Date(form.endsAt).toISOString() }) }))); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível criar o evento."); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-primary/35 p-0 sm:items-center sm:p-6"><form onSubmit={submit} className="w-full max-w-lg rounded-t-2xl bg-card p-6 shadow-2xl sm:rounded-2xl"><div className="mb-6 flex items-start justify-between"><div><p className="mono-label text-primary">Google Calendar / EA 2026</p><h2 className="mt-1 text-xl font-extrabold">Novo evento</h2></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-muted-foreground hover:bg-muted" aria-label="Fechar"><X size={18} /></button></div><div className="space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-bold">Título</span><input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Deputado estará em..." className="h-11 w-full rounded-lg border border-input bg-background px-3 text-sm" /></label><label className="block"><span className="mb-1.5 block text-xs font-bold">Cidade</span><select required value={form.cityId} onChange={(event) => setForm({ ...form, cityId: event.target.value })} className="h-11 w-full rounded-lg border border-input bg-background px-3 text-xs font-bold"><option value="">Selecione</option>{cities.map((city) => <option key={city.id} value={city.id}>{city.name} · {city.regionName}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1.5 block text-xs font-bold">Início</span><input required type="datetime-local" value={form.startsAt} onChange={(event) => setForm({ ...form, startsAt: event.target.value })} className="h-11 w-full rounded-lg border border-input bg-background px-2 text-xs" /></label><label><span className="mb-1.5 block text-xs font-bold">Fim</span><input required type="datetime-local" value={form.endsAt} onChange={(event) => setForm({ ...form, endsAt: event.target.value })} className="h-11 w-full rounded-lg border border-input bg-background px-2 text-xs" /></label></div><label className="block"><span className="mb-1.5 block text-xs font-bold">Local</span><input value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} className="h-11 w-full rounded-lg border border-input bg-background px-3 text-sm" /></label><label className="block"><span className="mb-1.5 block text-xs font-bold">Descrição / orientação</span><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="min-h-24 w-full rounded-lg border border-input bg-background p-3 text-sm" /></label></div>{error && <p className="mt-4 rounded-lg bg-destructive/5 p-3 text-xs font-bold text-destructive">{error}</p>}<button disabled={saving} className="mt-6 h-11 w-full rounded-lg bg-primary text-sm font-extrabold text-primary-foreground disabled:opacity-60">{saving ? "Criando no Google Calendar…" : "Criar evento e avisar a cidade"}</button></form></div>;
}