import { useMemo, useState } from 'react';
import { ArrowUpRight, ChevronDown, FileWarning, RefreshCw } from 'lucide-react';
import { Link } from 'wouter';
import { useListReviewIssues } from '@workspace/api-client-react';
import { EmptyState, ErrorState, LoadingRows, OpsShell, PageHeading, StatusPill } from '@/components/ops-shell';

export default function ReviewPage() {
  const [status, setStatus] = useState<'open' | 'resolved' | 'all'>('open');
  const params = useMemo(() => ({ status }), [status]);
  const query = useListReviewIssues(params);
  const issues = query.data ?? [];
  const severityTone = (severity: string) => severity === 'high' ? 'danger' : severity === 'medium' ? 'warning' : 'neutral';
  return <OpsShell>
    <PageHeading eyebrow="Qualidade / reconciliação" title="Fila de revisão" description="Resolva divergências sem romper a ligação entre o registro operacional e a fonte original." action={<button onClick={() => void query.refetch()} className="inline-flex items-center justify-center gap-2 rounded-lg border border-border px-4 py-3 text-xs font-extrabold hover:bg-muted" data-testid="button-refresh-issues"><RefreshCw size={14} /> Atualizar fila</button>} />
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-lg border border-border bg-card p-1">{(['open', 'resolved', 'all'] as const).map((value) => <button key={value} onClick={() => setStatus(value)} className={`rounded-md px-3 py-2 text-xs font-extrabold ${status === value ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground'}`} data-testid={`button-status-${value}`}>{value === 'open' ? 'Abertas' : value === 'resolved' ? 'Resolvidas' : 'Todas'}</button>)}</div><span className="mono-label text-muted-foreground">{issues.length} ocorrências nesta fila</span></div>
    {query.isLoading ? <LoadingRows count={4} /> : query.isError ? <ErrorState onRetry={() => void query.refetch()} /> : issues.length ? <div className="space-y-3" data-testid="issues-list">{issues.map((issue) => <article key={issue.id} className="rounded-2xl border border-border bg-card p-5 transition-colors hover:border-primary/30 sm:p-6" data-testid={`issue-card-${issue.id}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${issue.severity === 'high' ? 'bg-red-100 text-red-700' : issue.severity === 'medium' ? 'bg-amber-100 text-amber-700' : 'bg-muted text-muted-foreground'}`}><FileWarning size={18} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-extrabold">{issue.type}</h2><StatusPill tone={severityTone(issue.severity)}>{issue.severity === 'high' ? 'alta' : issue.severity === 'medium' ? 'média' : 'baixa'}</StatusPill><StatusPill tone={issue.status === 'resolved' ? 'success' : 'neutral'}>{issue.status === 'resolved' ? 'resolvida' : 'aberta'}</StatusPill></div><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{issue.details}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-[11px] text-muted-foreground"><span className="font-mono">Fonte: {issue.sourceSheet}</span><span className="font-mono">Linha: {issue.sourceRow}</span><span className="font-mono">ID liderança: {issue.leadershipId}</span></div></div><Link href={`/liderancas/${issue.leadershipId}`} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-extrabold hover:bg-muted" data-testid={`link-review-issue-${issue.id}`}>Abrir registro <ArrowUpRight size={13} /></Link></div></article>)}</div> : <EmptyState title={status === 'open' ? 'A fila está limpa' : 'Nenhuma ocorrência nesta visão'} detail={status === 'open' ? 'Não há registros abertos aguardando reconciliação.' : 'A API não retornou itens para este filtro.'} />}
    <section className="mt-7 rounded-2xl border border-border bg-card p-5 sm:p-6" data-testid="review-guidance"><div className="flex gap-3"><ChevronDown size={16} className="mt-1 text-primary" /><div><p className="text-sm font-extrabold">Como tratar uma ocorrência</p><p className="mt-1 max-w-3xl text-xs leading-5 text-muted-foreground">Abra o registro, confira a planilha e atualize apenas o campo divergente. A referência de origem permanece visível para auditoria da coordenação.</p></div></div></section>
  </OpsShell>;
}